ExtraUnbreakableMaterials:
- ANCIENT_DEBRIS
- NETHERITE_BLOCK
EnableCollisions: true
Abilities:
  Air:
    Evade:
      Enabled: false
      Description: As an airbender you can manipulate the streams of air around you
        quickly roll and evade potential attacks. Left click to use, the direction
        of your evasive maneuver depends on whether you are looking up or down.
      Cooldown: 500
    AirCombo:
      AirWheel:
        Enabled: false
        Description: Upgrade your airscooter to an airwheel that deals damage and
          knocks back nearby entities.
        Damage: 1.5
        Knockback: 1.5
        Cooldown: 6000
        AffectCooldown: 750
  Earth:
    MetalCable:
      Enabled: false
      Description: This incredibly versatile ability is used by Metalbenders for all
        purposes. Left click to launch a metal cable. If it connects to an entity
        or a block you will be pulled towards it. If you hold sneak, the entity or
        block will be pulled towards you instead. You can also left click again to
        throw any grabbed targets towards the direction you are looking at. Thrown
        blocks also deal damage. Note, depending on the server config, you might need
        some form of metal in your inventory to use this ability.
      Damage: 4.0
      BlockSpeed: 8.0
      Cooldown: 5000
      Range: 50
      RegenDelay: 10000
      RequiredItems:
      - IRON_INGOT
    EarthLine:
      SelectRange: 6
      PrisonCooldown: 15000
      PrisonDuration: 3000
      PrisonRadius: 0.8
      PrisonPoints: 8
      Enabled: false
      Description: Tap sneak while looking at an earthbendable block on the ground
        and then left click in a direction to launch a narrow line of earth towards
        your target to deal damage and knock them back. Additionally, you can hold
        sneak to control the direction of the line. Left clicking will cause spikes
        to erupt at the line's current location. Right click (you need an item in
        your offhand for right click to be detected if you are targeting air) instead
        to imprison your target without dealing damage.
      Damage: 3.0
      Cooldown: 3000
      Range: 24
      PrepareRange: 6
      AllowUnderWater: false
      Magma:
        RegenDelay: 20000
        DamageModifier: 2.0
        Regen: 20000
      Prison:
        Cooldown: 200
        Duration: 3000
        Radius: 0.1
        Points: 8
    EarthShot:
      SelectRange: 6
      AllowQuickLaunch: true
      Enabled: false
      Description: EarthShot is an offensive earth projectile move. Tap sneak while
        looking at a nearby earthbendable block and it will ascend to your eye height.
        Left click to launch your projectile. Once thrown, you can hold sneak to control
        its movement. If you are a Lavabender you can hold sneak while looking at
        your raised source to turn it into a more powerful MagmaShot!
      Damage: 2.0
      Cooldown: 2500
      Range: 90
      PrepareRange: 8
      MagmaShot:
        ChargeTime: 1500
        AllowConvert: true
        DamageModifier: 2.0
        PrepareTime: 1500
    EarthGlove:
      Enabled: false
      Description: Dai Li agents use this technique for various purposes. Hold sneak
        and click to launch your glove and attempt to grab your target. If you continue
        holding sneak, the gloves will attempt to return to you. You can also destroy
        other players' gloves by tapping sneak while looking at them. PROTOTYPE
      Damage: 4.0
      Cooldown: 6000
      Range: 75
      ClingPassive:
        Enabled: false
        Description: EarthGloves can be used to either slow or stop your descend while
          opposing a wall made of earthbendable materials. Hold sneak to use.
        Speed: 0.1
    EarthGuard:
      Enabled: false
      Description: This ability encases the Earthbender in temporary armor. To use,
        click on a block that is earthbendable, it will then fly towards you and grant
        you temporary armor and damage reduction. If you are a metalbender and it
        is a metal block, then you will get metal armor instead! Tap sneak with this
        ability bound to raise a small temporary wall to protect yourself from incoming
        attacks.
      Cooldown: 19900
      Duration: 8000
      SelectRange: 6
      BaseResistance: 1
      MetalResistance: 2
      WallDuration: 6000
      WallCooldown: 200
    LavaDisk:
      RegenDelay: 10000
      Enabled: false
      Description: Tap sneak to select a nearby earth or lava source. This disk made
        of molten earth will destroy any earthbendable and any soft materials it comes
        in contact with. The closer you are to the LavaDisk the faster it spins and
        the more damage it deals.
      MaxDamage: 2.0
      MinDamage: 0.5
      Cooldown: 11000
      Range: 24
      Regen: 10000
      PassThroughEntities: true
      AdditionalMeltableBlocks:
      - COBBLESTONE
      - ACACIA_LOG
      - BIRCH_LOG
      - DARK_OAK_LOG
      - JUNGLE_LOG
      - OAK_LOG
      - SPRUCE_LOG
      - ICE
      - PACKED_ICE
    MetalHook:
      Enabled: false
      Description: This ability is used by Metalbenders to launch metal grappling
        hooks, allowing them to easily maneuver terrain. To use this ability, you
        must have some form of iron in your inventory. Left click to launch a grappling
        hook, once attached it will automatically pull you towards it. Hold sneak
        or switch slots to disengage the hook.
      Cooldown: 1500
      Range: 30
      RequireItems: false
    EarthCombo:
      EarthShards:
        Enabled: false
        Description: Dai Li agents can disintegrate their earth gloves in multiple
          shards of rock and throw them at an enemy to damage them.
        Damage: 1.0
        Cooldown: 15000
        ShotCooldown: 100
        Range: 30
        AccuracyDrop: 0.1
        MaxShards: 15
  Fire:
    Bolt:
      Enabled: false
      Description: Hold sneak to charge up a lightning bolt. Once charged, release
        to discharge and strike the targeted location.
      Damage: 3.5
      Cooldown: 14000
      Range: 10
      ChargeTime: 700
    Combustion:
      Speed: 1.6
      RegenDelay: 15000
      FireTicks: 0
      ScaleDamageByDistance: false
      Enabled: true
      Description: Hold sneak to focus large amounts of energy into your body. Once
        charged, release shift to fire a powerful maneuverable Combustion beam Left
        click to detonate the beam manually.
      Damage: 2.0
      Cooldown: 17000
      Range: 75
      ChargeTime: 2000
      Power: 3
      MisfireModifier: -1
      RegenBlockTime: 7000
    FireCombo:
      FireWave:
        RequireSneaking: true
        Enabled: false
        Description: Master Jeong Jeong used this advanced technique to cast a great
          fire wave that grows in size while it advances forward.
        Damage: 3.0
        Cooldown: 16000
        Range: 17
        Duration: 1200
        MoveRate: 20
        MaxHeight: 7
        Width: 3
  Water:
    IceBreath:
      Enabled: false
      Description: As demonstrated by Katara, a Waterbender is able to freeze their
        breath. With this ability bound, simply hold sneak to charge and then release
        a breath of ice that freeze water and nearby entities.
      Damage: 3.0
      Range: 5
      Cooldown: 10000
      ChargeTime: 1000
      FrostDuration: 5000
    FrostBreath:
      Enabled: false
      Description: As demonstrated by Katara, a Waterbender is able to freeze their
        breath, causing anything it touches to be frozen! With this ability bound,
        simply hold sneak to start breathing frost!
      Damage: 2.0
      Range: 5
      Cooldown: 10000
      ChargeTime: 2000
      FrostDuration: 3000
    IceCrawl:
      SelectRange: 8
      Enabled: false
      Description: Tap sneak at a water or ice source block and then left click in
        a direction to launch forward a narrow line of ice. Upon colliding with an
        enemy, it deals damage and freezes the target's feet.
      Damage: 3.5
      Cooldown: 5000
      Range: 24
      PrepareRange: 8
      FreezeDuration: 2000
      IceDuration: 6000
    WaterCombo:
      IceDrill:
        SelectRange: 16
        RegenDelay: 10000
        Enabled: false
        Description: Given a large enough source of water or ice, a master waterbender
          is able to form a vast spike of ice capable of drilling through blocks.
        Cooldown: 11000
        SourceRange: 16
        MaxLength: 16
        Duration: 10000
        RegenBlockTime: 10000
